# An example Docker Compose file for Chlorobot/Chloresolver
services:
  chlorobot:
    build: ./
    env_file:
      - .env
  chloresolver:
    build: ./chloresolve
    depends_on:
      - chlorobot
    links:
      - "chlorobot:chlorobot_rpc"
    env_file:
      - .env