# An example Docker Compose file for Chlorobot/Chloresolver
services:
  chlorobot:
    build: ./
    env_file:
      - .env
  chloresolver:
    build: ./chloresolve
    depends_on:
      - chlorobot
    links:
      - "chlorobot:chlorobot-rpc"
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./chloresolve/tables/
        target: /home/chloresolve/tables/
volumes:
  db-tables:
