# An example Docker Compose file for Chlorobot/Chloresolver
services:
  chlorobot:
    build: ./
    env_file:
      - .env
  chloresolver:
    build: ./chloresolve
    depends_on:
      - chlorobot
    links:
      - "chlorobot:chlorobot-rpc"
    volumes:
      - chloresolver-log:/var/log/chloresolver
    env_file:
      - .env

volumes:
  chloresolver-log:
    