# An example Docker Compose file for Chlorobot/Chloresolver
services:
  chlorobot:
    build: ./
  chloresolver:
    build: ./chloresolve
    depends_on:
      - chlorobot
    links:
      - "chlorobot:chlorobot_rpc"